# Base configs
baseurl: "https://photo.tk-zh.com"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Tsong Khapa Patra"
subtitle: "See the world through my eyes!"
author: "Tsong Khapa Patra"
header:
 title: "Photography"
 subtitle: "by Tsong Khapa Patra"
footer:
 name: "Hey there, my name is Tsong Khapa"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/mba811/photography\">fork me on github</a> ;)"
web_design: ""
social_urls:
  facebook: ""
  twitter: "ztd811"
  instagram: ""
  dribbble: ""
  linkedin: ""
  github: "mba811"